### ISSUE TITLE
Footer not on the bottom of the page, clicking expand changes the height of main content

### ISSUE THREAD

**Issue by william1357chen** [JackyLai327/portfolio-2023#3]
#### Description
* Footer should be fixed on the bottom of the page
* Don't think clicking expand should change the height of the card. Lemme ask my UX friends about this and come back to this.

https://github.com/JackyLai327/portfolio-2023/assets/69340474/f387251b-6412-43fc-ba6e-9cc44b35b279

**Comment by JackyLai327** [comment]
that didn't happen on my end but i added code that i think will fix it
