### ISSUE TITLE
Hovering over skills icon changes the height of the entire page

### ISSUE THREAD

**Issue by william1357chen** [JackyLai327/portfolio-2023#4]
#### Description
* Visually this is a bit messy. I think allocating some height for the icon expansion will make it look better

https://github.com/JackyLai327/portfolio-2023/assets/69340474/04d48eec-4029-492a-af83-9fb60c1464b7

#### Hovering over certifications looks much better

https://github.com/JackyLai327/portfolio-2023/assets/69340474/8ebbed73-5e13-400f-8aba-1b3000336960

**Comment by JackyLai327** [comment]
fixed
